server {
    listen 80;
    server_name individual.honeypot;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name individual.honeypot;
    http2 on;
    server_tokens off;

    ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /usr/share/nginx/individualhoneypot;
    index index.html index.htm index.php;


    location / {
        try_files $uri $uri/ =404;
        # if ($request_method !~ ^(GET|POST)$) {
        #     return 405;
        # }
    add_header X-Frame-Options "DENY";
#Prevents clickjacking attacks by disallowing the site from being displayed in a <frame> or <iframe> on another website.
#Setting DENY means that no other website can embed this site’s content.
    add_header X-Content-Type-Options "nosniff";
#Prevents browsers from guessing ("sniffing") the content-type of files served by the server.
#By enforcing the nosniff option, this header reduces the risk of a browser interpreting files incorrectly.
    add_header Strict-Transport-Security "max-age=172800; includeSubDomains" always;
#Instructs browsers to connect only via HTTPS to this domain for a specified period and includes all subdomains.
#HSTS ensures that once a user connects over HTTPS, the browser will enforce HTTPS connections for future visits.

    }

    location ~ \.php$ {
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
    # Enable ModSecurity
    modsecurity on;
    modsecurity_rules_file /etc/nginx/modsec/main.conf;
}
