server {
    listen 80;
    server_name honeypot08;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name honeypot08;
    http2 on;
    server_tokens off;

    ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /usr/share/nginx/HoneyPot08;
    index index.html index.htm index.php;


    location / {
        try_files $uri $uri/ =404;
        # if ($request_method !~ ^(GET|POST)$) {
        #     return 405;
        # }
    add_header X-Frame-Options "DENY";  # XFO
    add_header X-Content-Type-Options "nosniff";  # XCTO
    add_header Strict-Transport-Security "max-age=172800; includeSubDomains" always;  # HSTS

    }

    location ~ \.php$ {
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
